/**
 * Defines all the possible mutations that can be carried out on the Vuex store.
 */

 export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

 // Dashboard mutations
 export const SAVE_DASHBOARD_DATA_TO_STORE = 'SAVE_DASHBOARD_DATA_TO_STORE';
 export const SAVE_NEWSFEED_TO_STORE = 'SAVE_NEWSFEED_TO_STORE';

 // User store module mutations
 export const SAVE_AUTHENTICATED_USER_TO_STORE = 'SAVE_AUTHENTICATED_USER_TO_STORE';
 export const SAVE_USER_STOCKBROKING_DATA_TO_STORE = 'SAVE_USER_STOCKBROKING_DATA_TO_STORE';
 export const SAVE_USER_FIXEDINCOME_DATA_TO_STORE = 'SAVE_USER_FIXEDINCOME_DATA_TO_STORE ';
 export const SAVE_USER_CASH_DATA_TO_STORE = 'SAVE_USER_CASH_DATA_TO_STORE';

 // Stockbroking module mutations
 export const SAVE_TRADE_ORDERS_TO_STORE = 'SAVE_TRADE_ORDERS_TO_STORE';
 export const SAVE_MARKET_DATA_TO_STORE = 'SAVE_MARKET_DATA_TO_STORE';
 export const CHANGE_CURRENT_PORTFOLIO = 'CHANGE_CURRENT_PORTFOLIO';

// Cash Account Mutations
 export const CHANGE_SELECTED_CASH_ACCOUNT = 'CHANGE_SELECTED_CASH_ACCOUNT';
 export const SET_NAIRA_CASH_STATEMENTS = 'SET_NAIRA_CASH_STATEMENTS';
 export const SET_NAIRA_SEARCH_START_DATE = 'SET_NAIRA_SEARCH_START_DATE';
 export const SET_NAIRA_SEARCH_END_DATE = 'SET_NAIRA_SEARCH_END_DATE';
